### PR TITLE
Update Gradle wrapper to Gradle 4.1

### PR DESCRIPTION
**Pull request by eriwen**
Gradle 4.1 is _far_ faster than 3.1, and will allow us to take advantage of Gradle's [Kotlin DSL](https://github.com/gradle/kotlin-dsl) later, among other things.

Go Kotlin or go home ;)

### Testing Done
Successfully ran backend and frontend and tested all main routes through the browser. Are there other tests I ought to run for future contributions?

### CODE REVIEW

**Comment by cy6erGn0m** [comment]
Hm, I used to think that it doesn't work with 4.x. On which OS have you tried this?

**Comment by eriwen** [comment]
@cy6erGn0m I tested it with macOS. Can you recall any specific failure you were getting on Gradle 4.x?

**Comment by cy6erGn0m** [comment]
I was experiencing native incompatibility caused by ruby grapefruit process launcher. Perhaps I have to try it again

**Comment by cy6erGn0m** [comment]
@eriwen Have tried it and it works well. However it dosn't with 4.2.x

**Comment by cy6erGn0m** [comment]
Thanks!

**Comment by eriwen** [comment]
I was about to investigate, but it seems like you got it working with 4.2 :)

**Pull request merged**
